In [2]:
import pandas as pd 
import numpy as np 
import os 
import matplotlib.pyplot as plt

In [3]:
os.chdir('C:\\Users\\admin\\Desktop\\mandy\\Mandeep\\Case study\\Python Case Study\\end to end\\5. Python Foundation End to End Case Study_E-Commerce Analytics Project')

In [4]:
Customers = pd.read_csv('CUSTOMERS.csv')
Sellers = pd.read_csv('SELLERS.csv')
Products= pd.read_csv('PRODUCTS.csv')
Orders = pd.read_csv('ORDERS.csv')
Order_item = pd.read_csv('ORDER_ITEMS.csv')
Order_Payments = pd.read_csv('ORDER_PAYMENTS.csv')
Order_Review_Ratings = pd.read_csv('ORDER_REVIEW_RATINGS.csv')
Geo_Location = pd.read_csv('GEO_LOCATION.csv')

In [5]:
Customers.head(1)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,Adilabad,Andhra Pradesh

In [6]:
Sellers.head(1)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,Alwal,Andhra Pradesh

In [9]:
Products.head(1)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,Perfumery,40.0,287.0,1.0,225.0,16.0,10.0,14.0

In [57]:
Orders.head(1)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,OrderMonth,group_belongs,group_index
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:00,10/2/2017 11:07,10/4/2017 19:55,10/10/2017 21:25,10/18/2017 0:00,2017-10,2017-10,0

In [59]:
Order_item.head(1)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,Total_Revenue
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,9/19/2017 9:45,58.9,13.29,72.19

In [12]:
Order_Payments.head(1)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33

In [13]:
Order_Review_Ratings.head(1)

,review_id,order_id,review_score,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,1/18/2018 0:00,1/18/2018 21:46

In [14]:
Geo_Location.head(1)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,Akkarampalle,Andhra Pradesh

<hr style="border: 2px solid black;">

In [15]:
# Total Revenue
Order_item['Total_Revenue']= Order_item['price']+Order_item['freight_value']
total_revenue =  Order_item['Total_Revenue'].sum()

# Total Quantity
total_quantity = Order_item.shape[0]

# Total Products
total_products =Products.shape[0]

# Total Categories
total_categories = Products['product_category_name'].nunique()

#Total Sellers
total_sellers = Sellers.shape[0]

#Total Locations
total_locations = Geo_Location.shape[0]

# Total Channels 
total_channels = Order_Payments['payment_type'].nunique()

print("Total_Revenue:",total_revenue)
print("Total_Quantity:",total_quantity)
print("Total_Products:",total_products)
print("Total_Cateegories:",total_categories)
print("Total_Sellers:",total_sellers)
print("Total_Locations:",total_locations)
print("Total_Channels:",total_channels)

Total_Revenue: 15843553.24
Total_Quantity: 112650
Total_Products: 32951
Total_Cateegories: 71
Total_Sellers: 3095
Total_Locations: 19015
Total_Channels: 5

In [16]:
customer_orders = pd.merge(left=Customers,right=Orders,on='customer_id' , how='left' )

In [17]:
customer_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   customer_id                    99441 non-null  object
 1   customer_unique_id             99441 non-null  object
 2   customer_zip_code_prefix       99441 non-null  int64
 3   customer_city                  99441 non-null  object
 4   customer_state                 99441 non-null  object
 5   order_id                       99441 non-null  object
 6   order_status                   99441 non-null  object
 7   order_purchase_timestamp       99441 non-null  object
 8   order_approved_at              99281 non-null  object
 9   order_delivered_carrier_date   97658 non-null  object
 10  order_delivered_customer_date  96476 non-null  object
 11  order_estimated_delivery_date  99441 non-null  object
dtypes: int64(1), object(11)
memory usage: 9.1+ MB

In [18]:
# converting Dtype of order_purchase_timestamp to datetime 
customer_orders['order_purchase_timestamp'] = pd.to_datetime(customer_orders['order_purchase_timestamp'])

# Find first order date per customer
first_orders = customer_orders.groupby('customer_id')['order_purchase_timestamp'].min().reset_index()

# Extract year-month for first purchase
first_orders['month'] = first_orders['order_purchase_timestamp'].dt.to_period('M')

# Count new customers per month
new_customers_by_month = first_orders['month'].value_counts().sort_index()

# Convert to DataFrame for display
new_customers_df = new_customers_by_month.reset_index()
new_customers_df.columns = ['Month', 'New_Customers']

print(new_customers_df)

      Month  New_Customers
0   2016-09              4
1   2016-10            324
2   2016-12              1
3   2017-01            800
4   2017-02           1780
5   2017-03           2682
6   2017-04           2404
7   2017-05           3700
8   2017-06           3245
9   2017-07           4026
10  2017-08           4331
11  2017-09           4285
12  2017-10           4631
13  2017-11           7544
14  2017-12           5673
15  2018-01           7269
16  2018-02           6728
17  2018-03           7211
18  2018-04           6939
19  2018-05           6873
20  2018-06           6167
21  2018-07           6292
22  2018-08           6512
23  2018-09             16
24  2018-10              4

In [19]:
# Convert to datetime
Orders['order_purchase_timestamp'] = pd.to_datetime(Orders['order_purchase_timestamp'])

# Create 'OrderMonth' and 'group_belongs'
Orders['OrderMonth'] = Orders['order_purchase_timestamp'].dt.to_period('M')
Orders['group_belongs'] = Orders.groupby('customer_id')['order_purchase_timestamp'].transform('min').dt.to_period('M')

In [20]:
from operator import attrgetter 
# Calculate group index (how many months since first purchase)
Orders['group_index'] = (Orders['OrderMonth'] - Orders['group_belongs']).apply(attrgetter('n'))

In [21]:
# Count customers per group and group index
group_data = Orders.groupby(['group_belongs', 'group_index'])['customer_id'].nunique().reset_index()

# Pivot table: Retention matrix
group_pivot = group_data.pivot(index='group_belongs', columns='group_index', values='customer_id')

In [22]:
group_size = group_pivot.iloc[:,0]
retention = group_pivot.divide(group_size, axis=0).round(3)

print("Retention Table (Month-over-Month %):")
print(retention.fillna(0) * 100)

Retention Table (Month-over-Month %):
group_index        0
group_belongs
2016-09        100.0
2016-10        100.0
2016-12        100.0
2017-01        100.0
2017-02        100.0
2017-03        100.0
2017-04        100.0
2017-05        100.0
2017-06        100.0
2017-07        100.0
2017-08        100.0
2017-09        100.0
2017-10        100.0
2017-11        100.0
2017-12        100.0
2018-01        100.0
2018-02        100.0
2018-03        100.0
2018-04        100.0
2018-05        100.0
2018-06        100.0
2018-07        100.0
2018-08        100.0
2018-09        100.0
2018-10        100.0

In [24]:
# Revenues from existing / new customers on month on month basis

In [25]:
Orders_Order_items = pd.merge(Orders,Order_item,on=('order_id'),how='left')

In [26]:
Orders_Order_items[Orders_Order_items['group_index']==0]

# As All customers are new 
monthly_revenue = Orders_Order_items.groupby('OrderMonth')['Total_Revenue'].sum().reset_index()
monthly_revenue.rename(columns={'Total_Revenue': 'Monthly_Total_Revenue'}, inplace=True)
print(monthly_revenue)

   OrderMonth  Monthly_Total_Revenue
0     2016-09                 354.75
1     2016-10               56808.84
2     2016-12                  19.62
3     2017-01              137188.49
4     2017-02              286280.62
5     2017-03              432048.59
6     2017-04              412422.24
7     2017-05              586190.95
8     2017-06              502963.04
9     2017-07              584971.62
10    2017-08              668204.60
11    2017-09              720398.91
12    2017-10              769312.37
13    2017-11             1179143.77
14    2017-12              863547.23
15    2018-01             1107301.89
16    2018-02              986908.96
17    2018-03             1155126.82
18    2018-04             1159698.04
19    2018-05             1149781.82
20    2018-06             1022677.11
21    2018-07             1058728.03
22    2018-08             1003308.47
23    2018-09                 166.46
24    2018-10                   0.00

In [27]:
Orders_Order_items[Orders_Order_items['group_index']!=0]
# no existing customer order anything

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, OrderMonth, group_belongs, group_index, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value, Total_Revenue]
Index: []

#### Category wise Sales and Quantity

In [73]:
Product_Order_item = pd.merge(Order_item,Products,on='product_id',how='left')
category_Revenue_quantity = Product_Order_item.groupby('product_category_name').agg(
    Total_Revenue=('Total_Revenue', 'sum'),
    Total_Quantity=('product_category_name', 'count')
).reset_index()

In [95]:
category_Revenue_quantity

         product_category_name  Total_Revenue  Total_Quantity
0   Agro_Industry_And_Commerce       78374.07             212
1             Air_Conditioning       61774.19             297
2                          Art       28247.81             209
3        Arts_And_Craftmanship        2184.14              24
4                        Audio       56398.94             364
..                         ...            ...             ...
66                  Stationery      277741.71            2517
67      Tablets_Printing_Image        8754.61              83
68                   Telephony      394883.32            4545
69                        Toys      561372.55            4117
70               Watches_Gifts     1305541.61            5991

[71 rows x 3 columns]

#### Total_Revenue , Total Quantity from each City & State

In [87]:
Sellers_Order_item = pd.merge(Order_item,Sellers,on='seller_id',how='left')
Sellers_Order_item.groupby(['seller_city','seller_state']).agg(
    Total_Revenue=('Total_Revenue', 'sum'),
    Total_Quantity=('seller_id', 'count')
)

                                Total_Revenue  Total_Quantity
seller_city  seller_state
Aadityana    Gujarat                   203.48               3
Aarambhada   Gujarat                  1621.78              25
Achabal      Jammu & Kashmir            77.38               1
Adalaj       Gujarat                  2697.83              16
Adilabad     Andhra Pradesh          99693.00             646
...                                       ...             ...
Yellandu     Andhra Pradesh            401.24               6
Yemmiganur   Andhra Pradesh          11703.10              46
Zahirabad    Andhra Pradesh          58434.37             393
Ziauddin Pur Delhi                   34071.26             240
Ziro         Arunachal Pradesh         555.49              15

[534 rows x 2 columns]

#### Trend by month/week/day/hour

In [97]:
Orders['Month'] = Orders['order_purchase_timestamp'].dt.to_period('M')
Orders['Week'] = Orders['order_purchase_timestamp'].dt.isocalendar().week
Orders['Day'] = Orders['order_purchase_timestamp'].dt.day_name()
Orders['Hour'] = Orders['order_purchase_timestamp'].dt.hour

#### Trend by month

In [119]:
Orders_Order_item = pd.merge(Order_item,Orders,on='order_id',how='left')
Orders_Order_item.groupby('Month').agg(
    Total_Revenue=('Total_Revenue', 'sum'),
    Total_Quantity=('order_id', 'count')
)

         Total_Revenue  Total_Quantity
Month
2016-09         354.75               6
2016-10       56808.84             363
2016-12          19.62               1
2017-01      137188.49             955
2017-02      286280.62            1951
2017-03      432048.59            3000
2017-04      412422.24            2684
2017-05      586190.95            4136
2017-06      502963.04            3583
2017-07      584971.62            4519
2017-08      668204.60            4910
2017-09      720398.91            4831
2017-10      769312.37            5322
2017-11     1179143.77            8665
2017-12      863547.23            6308
2018-01     1107301.89            8208
2018-02      986908.96            7672
2018-03     1155126.82            8217
2018-04     1159698.04            7975
2018-05     1149781.82            7925
2018-06     1022677.11            7078
2018-07     1058728.03            7092
2018-08     1003308.47            7248
2018-09         166.46               1

#### Trend by Week

In [123]:
Orders_Order_item.groupby('Week').agg(
    Total_Revenue=('Total_Revenue', 'sum'),
    Total_Quantity=('order_id', 'count')
)

      Total_Revenue  Total_Quantity
Week
1         217144.60            1608
2         291467.36            2093
3         289401.81            2199
4         312737.29            2217
5         315122.89            2363
6         327091.12            2349
7         290868.24            2328
8         304990.03            2451
9         385635.26            2714
10        360207.52            2529
11        365704.24            2499
12        369842.63            2723
13        338491.09            2309
14        370737.31            2453
15        340219.79            2283
16        373784.20            2573
17        382493.66            2686
18        402629.42            2898
19        471837.30            3187
20        442557.38            3188
21        287584.36            1991
22        343023.70            2146
23        368231.41            2614
24        379038.06            2576
25        332432.45            2388
26        332187.88            2417
27        312579.84            2257
28        329190.18            2188
29        406739.32            2965
30        418662.95            2948
31        468544.27            3403
32        478644.39            3316
33        437632.53            3222
34        272969.36            2243
35        217394.43            1274
36        154094.46            1009
37        186169.27            1304
38        151437.66            1136
39        167220.52            1090
40        218862.02            1456
41        183456.08            1235
42        190624.86            1340
43        160982.07            1145
44        165560.25            1101
45        186728.67            1362
46        205865.61            1502
47        474623.65            3497
48        312437.42            2374
49        258850.66            1875
50        218401.00            1571
51        151022.06            1095
52        119398.71             960

#### Trend by day

In [126]:
Orders_Order_item.groupby('Day').agg(
    Total_Revenue=('Total_Revenue', 'sum'),
    Total_Quantity=('order_id', 'count')
)

           Total_Revenue  Total_Quantity
Day
Friday        2281931.02           16039
Monday        2600533.82           18393
Saturday      1752075.49           12168
Sunday        1858518.47           13416
Thursday      2351584.20           16797
Tuesday       2532228.11           18237
Wednesday     2466682.13           17600

#### Trend by Hour

In [129]:
Orders_Order_item.groupby('Hour').agg(
    Total_Revenue=('Total_Revenue', 'sum'),
    Total_Quantity=('order_id', 'count')
)

      Total_Revenue  Total_Quantity
Hour
0         371018.90            2717
1         174479.00            1289
2          65526.06             584
3          41319.89             314
4          28334.08             244
5          26175.23             218
6          67452.45             556
7         179761.85            1377
8         458449.50            3377
9         790252.51            5449
10        975972.35            7034
11       1023074.93            7432
12        986082.17            6819
13       1015875.62            7403
14       1100743.07            7565
15       1052986.78            7370
16       1090233.44            7653
17        979469.54            7010
18        954038.98            6550
19        958005.52            6716
20        995339.27            6875
21        975604.70            6920
22        918025.73            6541
23        615331.67            4637

#### Total_sales and quantity sold using payments method

In [134]:
Order_payment_items = pd.merge(Order_item,Order_Payments,on='order_id',how='left')
Order_payment_items.groupby('payment_type').agg(
    Total_Revenue=('Total_Revenue', 'sum'),
    Total_Quantity=('order_id', 'count')
)

              Total_Revenue  Total_Quantity
payment_type
UPI              2842240.29           22867
credit_card     12723914.88           86769
debit_card        215306.74            1691
voucher           785081.94            6274

In [146]:
merged = Order_item.merge(Orders[['order_id', 'order_purchase_timestamp']], on='order_id', how='left') \
                    .merge(Products[['product_id', 'product_category_name']], on='product_id', how='left') \
                    .merge(Sellers[['seller_id', 'seller_state']], on='seller_id', how='left')

In [150]:
merged['Month'] = pd.to_datetime(merged['order_purchase_timestamp']).dt.to_period('M')

#### Top Products of each month

In [208]:
Top_by_month = merged.sort_values( ['Total_Revenue','Month'], ascending=[False,True]).groupby('Month').head(1)
Top_by_month[['Month', 'Total_Revenue', 'product_id']]

          Month  Total_Revenue                        product_id
3556    2017-02        6929.31  489ae2aa008f021502940f251d4cce7f
112233  2018-07        6922.21  69c590f7ffc7bf8db97190b6cb6ed62e
107841  2017-05        6726.66  1bdf5e6731585cf01aa8169c7028d6ad
74336   2017-04        4950.34  a6492cc69376c469ab6f61d8f44de961
62086   2018-06        4681.78  259037a6a41845e455183f89c5035f18
29193   2018-08        4513.32  a1beef8f3992dbd4cd8726796aa69c53
45843   2018-03        4175.26  6cdf8fc1d741c76586d8b6b15e9eef30
59137   2017-03        4016.91  6902c1962dd19d540807d0ab8fade5c6
28884   2018-05        3979.55  0563d4cc419141eab2e5b438046e844e
72452   2018-01        3826.80  dd113cb02b2af9c8e5787e8f1f0722f6
25648   2018-04        3526.46  34f99d82cfc355d08d8db780d14aa002
107190  2017-12        3297.40  0c104824e973388d487c67a3d346e96d
95091   2017-11        3184.55  2b69866f22de8dad69c976771daba91c
21844   2018-02        3155.82  6054d161235b97a4aaccea2a086d30b8
4850    2017-10        3126.50  34f99d82cfc355d08d8db780d14aa002
53535   2017-06        3048.27  470433f95ba906e17efac3fce39e9ffd
36542   2017-07        3041.73  470433f95ba906e17efac3fce39e9ffd
38895   2017-01        3016.01  8b502ca34e28d30605bc667b965b6abf
57941   2017-08        2692.82  122bedead6e7541d311e6e0ab3cf248f
89532   2017-09        1963.97  b7d35019c9f8e0eeff52b36a59eec8e8
82796   2016-10        1423.55  fd8a5b9a8a79d7ba0739d69be5dc5aa1
37073   2018-09         166.46  b98992ea80b467987a7fbb88e7f2076a
101394  2016-09          75.06  f3c2d01a84c947b078e32bbef0718962
83342   2016-12          19.62  f5d8f4fbc70ca2a0038b9a0010ed5cb0

#### Top product by seller

In [215]:
Top_by_seller = merged.sort_values( ['Total_Revenue'], ascending=[False]).groupby('seller_id').head(1)
Top_by_seller[['seller_id', 'Total_Revenue', 'product_id']]

,seller_id,Total_Revenue,product_id
3556,e3b4998c7a498169dc7bce44e6bb6277,6929.31,489ae2aa008f021502940f251d4cce7f
112233,80ceebb4ee9b31afb6c6a916a574a1e2,6922.21,69c590f7ffc7bf8db97190b6cb6ed62e
107841,ee27a8f15b1dded4d213a468ba4eb391,6726.66,1bdf5e6731585cf01aa8169c7028d6ad
74336,59417c56835dd8e2e72f91f809cd4092,4950.34,a6492cc69376c469ab6f61d8f44de961
62086,c72de06d72748d1a0dfb2125be43ba63,4681.78,259037a6a41845e455183f89c5035f18
...,...,...,...
125,702835e4b785b67a084280efca355756,18.56,a9c404971d1a5b1cbc2e4070e02731fd
94526,4965a7002cca77301c82d3f91b82e1a9,16.36,3b68252831a799e9e109e44967b61422
91383,1fa2d3def6adfa70e58c276bb64fe5bb,15.90,24543438ec09114a42a153f76ae693f2
73455,77128dec4bec4878c37ab7d6169d6f26,15.22,639a641dfdddb9367d030768148076b1
87922,cf6f6bc4df3999b9c6440f124fb2f687,12.22,5304ff3fa35856a156e1170a6022d34d

#### Top product by state

In [220]:
Top_by_state = merged.sort_values( ['Total_Revenue'], ascending=[False]).groupby('seller_state').head(1)
Top_by_state[['seller_state', 'Total_Revenue', 'product_id']]

             seller_state  Total_Revenue                        product_id
3556       Andhra Pradesh        6929.31  489ae2aa008f021502940f251d4cce7f
112233              Delhi        6922.21  69c590f7ffc7bf8db97190b6cb6ed62e
74336        Chhattisgarh        4950.34  a6492cc69376c469ab6f61d8f44de961
62086             Gujarat        4681.78  259037a6a41845e455183f89c5035f18
25648          Tamil Nadu        3526.46  34f99d82cfc355d08d8db780d14aa002
110583            Haryana        2626.07  5263b67de8e3edbade45ea923f6c4e79
59703           Karnataka        2457.44  a859dc323c1bebb21c887054599fccce
58808         Maharashtra        2133.69  b7550710491181180a97295a6b9faded
16564    Himachal Pradesh        1783.70  f3f12eabcd090650146791b249f48880
46516      Madhya Pradesh        1657.57  a3aab6d23ab543e36652264fce5ed7be
25893              Kerala        1488.33  dbf4588317c84ec9cde32b033de522e4
14272   Arunachal Pradesh        1435.97  864413ca56c2bcea359a213956a922c0
108801    Jammu & Kashmir        1244.74  34f7bddc98259b62a001644be7928e43
75504           Rajasthan         949.62  33d572fab2a1a7c217d8831ade7d9357
94366       Uttar Pradesh         836.29  d9e77a9aeffd10aa1a6f2d0ad00608ac
67155              Punjab         609.24  d9ba932a269adb3893a1d7e53161c7d2
111132        West Bengal         592.42  d14495a85be157b5cacef4eaaf825791
54304              Orissa         443.57  13c7f5f30c37ace12ec243d2ebb8e970
111355        Uttaranchal          83.45  22cae88a3d0dfb90553827c761728e55

#### Top Product by Category

In [225]:
Top_by_Category = merged.sort_values( ['Total_Revenue'], ascending=[False]).groupby('product_category_name').head(1)
Top_by_Category[['product_category_name', 'Total_Revenue', 'product_id']]

,product_category_name,Total_Revenue,product_id
3556,Housewares,6929.31,489ae2aa008f021502940f251d4cce7f
112233,Computers,6922.21,69c590f7ffc7bf8db97190b6cb6ed62e
107841,Art,6726.66,1bdf5e6731585cf01aa8169c7028d6ad
74336,Small_Appliances,4950.34,a6492cc69376c469ab6f61d8f44de961
29193,Musical_Instruments,4513.32,a1beef8f3992dbd4cd8726796aa69c53
...,...,...,...
47295,Fashion_Underwear_Beach,208.09,b8c91645bd166cdc9feb8795a186cef7
53345,Diapers_And_Hygiene,158.97,53e695484b71a194bf7d89b48700756a
104990,Fashion_Childrens_Clothes,124.52,0ab3ab3b2869073aa9afe795fe9151aa
55788,Cds_Dvds_Musicals,117.58,1dceebcc5f23c02ea23e16d5bedca000
53476,Flowers,77.63,be0e6c61c2bcdd9a4d022ba67fd66189

#### Popular categories for each state `

In [303]:
Category_by_state = merged.groupby(['seller_state', 'product_category_name']).agg(
    Total_Revenue=('Total_Revenue', 'sum'),
    Total_Quantity=('order_item_id', 'count')
).sort_values('Total_Quantity', ascending=False).groupby('seller_state').head(1)

In [305]:
Category_by_state

,,Total_Revenue,Total_Quantity
seller_state,product_category_name,,
Andhra Pradesh,Health_Beauty,1067627.96,7639
Gujarat,Bed_Bath_Table,634575.20,6312
Chhattisgarh,Housewares,97829.71,664
Haryana,Computers_Accessories,109605.15,534
Karnataka,Furniture_Decor,44954.58,505
West Bengal,Garden_Tools,72503.69,425
Jammu & Kashmir,Sports_Leisure,44094.05,409
Arunachal Pradesh,Sports_Leisure,51043.22,400
Madhya Pradesh,Sports_Leisure,52382.14,343
Delhi,Health_Beauty,40957.28,279
Rajasthan,Luggage_Accessories,26291.73,273
Maharashtra,Toys,17879.52,201
Himachal Pradesh,Sports_Leisure,19968.95,161
Uttar Pradesh,Construction_Tools_Construction,16273.48,83
Kerala,Housewares,5332.40,73
Tamil Nadu,Health_Beauty,6914.76,63
Orissa,Housewares,11695.05,61
Uttaranchal,Health_Beauty,1846.41,38
Punjab,Housewares,1553.51,15

In [307]:
Category_by_Month = merged.groupby(['Month', 'product_category_name']).agg(
    Total_Revenue=('Total_Revenue', 'sum'),
    Total_Quantity=('order_item_id', 'count')
).sort_values('Total_Quantity', ascending=False).groupby('Month').head(1)

In [309]:
Category_by_Month

                                                 Total_Revenue  Total_Quantity
Month   product_category_name
2018-02 Computers_Accessories                        118128.67             981
2017-11 Bed_Bath_Table                               106669.19             975
2018-06 Health_Beauty                                125197.75             885
2018-08 Health_Beauty                                137206.07             849
2018-01 Bed_Bath_Table                                90827.19             848
2018-03 Bed_Bath_Table                                84107.25             798
2018-07 Health_Beauty                                122743.98             784
2018-05 Health_Beauty                                110477.15             770
2018-04 Bed_Bath_Table                                86731.40             746
2017-07 Bed_Bath_Table                                74629.84             579
2017-12 Bed_Bath_Table                                59896.26             552
2017-10 Bed_Bath_Table                                55448.85             545
2017-09 Bed_Bath_Table                                62177.20             533
2017-08 Bed_Bath_Table                                66297.02             512
2017-06 Bed_Bath_Table                                41684.51             382
2017-05 Bed_Bath_Table                                39705.14             369
2017-03 Furniture_Decor                               29506.43             328
2017-04 Bed_Bath_Table                                29007.36             274
2017-02 Furniture_Decor                               26262.32             266
2017-01 Furniture_Decor                               16461.75             182
2016-10 Furniture_Decor                                7052.28              67
2016-09 Health_Beauty                                   143.46               3
2016-12 Fashion_Bags_Accessories                         19.62               1
2018-09 Kitchen_Dining_Laundry_Garden_Furniture         166.46               1

#### Top 10 most expensive products

In [318]:
top_by_price = merged.sort_values('price', ascending=False)
top_by_price[['product_id','price']].head(10)

                              product_id    price
3556    489ae2aa008f021502940f251d4cce7f  6735.00
112233  69c590f7ffc7bf8db97190b6cb6ed62e  6729.00
107841  1bdf5e6731585cf01aa8169c7028d6ad  6499.00
74336   a6492cc69376c469ab6f61d8f44de961  4799.00
11249   c3ed642d592594bb648ff4a04cee2747  4690.00
62086   259037a6a41845e455183f89c5035f18  4590.00
29193   a1beef8f3992dbd4cd8726796aa69c53  4399.87
45843   6cdf8fc1d741c76586d8b6b15e9eef30  4099.99
78310   dd113cb02b2af9c8e5787e8f1f0722f6  4059.00
59137   6902c1962dd19d540807d0ab8fade5c6  3999.90

<hr style="border: 2px solid black;">
<hr style="border: 2px solid black;">

## Q-2

In [352]:
Customers_Order_item = Customers.merge(
    Orders[['order_id', 'customer_id']], on='customer_id', how='right'
).merge(
    Order_item[['order_id', 'Total_Revenue']], on='order_id', how='left'
)

In [378]:
Customers_Order_item['Revenue_Group'] = pd.qcut(Customers_Order_item['Total_Revenue'], q=4, labels=['Low', 'Medium', 'High', 'Very High'])

In [380]:
Customers_Order_item[['customer_id','Total_Revenue','Revenue_Group']].head()

                        customer_id  Total_Revenue Revenue_Group
0  9ef432eb6251297304e76186b10a928d          38.71           Low
1  b0830fb4747a6c6d20dea0b8c802d7ef         141.46          High
2  41ce2a54c0b03bf3443c3d931a367089         179.12     Very High
3  f88197465ea7920adcdbec7375364d82          72.20        Medium
4  8ab97904e6daea8866dbdbc4fb7aad2c          28.62           Low

In [382]:
Sellers_Order_item['Revenue_Group']=pd.qcut(Sellers_Order_item['Total_Revenue'],q=4,labels=['Low', 'Medium', 'High', 'Very High'])
Sellers_Order_item[['seller_id','Total_Revenue','Revenue_Group']].head()

                          seller_id  Total_Revenue Revenue_Group
0  48436dade18ac8b2bce089ec2a041202          72.19        Medium
1  dd7ddc04e1b6c2c614352b383efe2d36         259.83     Very High
2  5b51032eddd242adc84c38acab88f23d         216.87     Very High
3  9d7a1d34a5052409006425275ba1c2b4          25.78           Low
4  df560393f3a51e74553ab94004ba5c87         218.04     Very High

<hr style="border: 2px solid black;">
<hr style="border: 2px solid black;">

## Q-3

In [649]:
from itertools import combinations
from collections import Counter

# Group products by order_id
order_products = Order_item.groupby('order_id')['product_id'].apply(list)

# Filter orders with 2 or more products
order_products = order_products[order_products.apply(lambda x: len(x) >= 2)]

# Generate all combinations of size 2 or 3
all_combinations = []
for products in order_products:
    combos = list(combinations(sorted(products), 2))  # use 3 for triplets if needed
    all_combinations.extend(combos)

# Count frequency of each combination
combo_counts = Counter(all_combinations)

# Convert to DataFrame and get top 10
top_combos = pd.DataFrame(combo_counts.most_common(10), columns=['Product_Combination', 'Frequency'])

print(top_combos)

                                 Product_Combination  Frequency
0  (422879e10f46682990de24d770e7f83d, 422879e10f4...        279
1  (ee3d532c8a438679776d222e997606b3, ee3d532c8a4...        195
2  (9571759451b1d780ee7c15012ea109d4, 9571759451b...        190
3  (a62e25e09e05e6faf31d90c6ec1aa3d1, a62e25e09e0...        141
4  (368c6c730842d78016ad823897a372db, 368c6c73084...        139
5  (b532349fe46b38fbc7bb3914c1bdae07, b532349fe46...        134
6  (d5991653e037ccb7af6ed7d94246b249, d5991653e03...        123
7  (53759a2ecddad2bb87a079a1f1519f73, 53759a2ecdd...        119
8  (89b190a046022486c635022524a974a8, 89b190a0460...        115
9  (aca2eb7d00ea1a7b8ebd4e68314663af, aca2eb7d00e...        111

<hr style="border: 2px solid black;">
<hr style="border: 2px solid black;">

## Q-4

#### Payment methods by customers

In [418]:
print('Customers are paying using:')
payment_methods =Order_Payments['payment_type'].unique()
print(payment_methods)

Customers are paying using:
['credit_card' 'UPI' 'voucher' 'debit_card' 'not_defined']

#### Most used payment method

In [455]:
Order_Payments.groupby('payment_type').agg(Used=('order_id','count')).iloc[0:1]

               Used
payment_type
UPI           19784

<hr style="border: 2px solid black;">
<hr style="border: 2px solid black;">

## Q-5

In [462]:
merged_rating = Order_Review_Ratings.merge(Order_item,on='order_id',how='left')\
                                           .merge(Sellers,on='seller_id',how='left')\
                                        .merge(Products,on= 'product_id',how='left')

In [541]:
# product Category top 10 maximum rating
merged_rating.groupby(['product_category_name','review_score']).agg(Count=('order_id','count')).sort_values(['review_score','Count'],ascending=[False ,False]).head(10)

                                    Count
product_category_name review_score
Health_Beauty         5              5870
Bed_Bath_Table        5              5795
Sports_Leisure        5              5129
Furniture_Decor       5              4462
Computers_Accessories 5              4204
Housewares            5              3988
Watches_Gifts         5              3335
Toys                  5              2518
Garden_Tools          5              2482
Auto                  5              2383

In [543]:
# minimum 10 ratings by product category
merged_rating.groupby(['product_category_name','review_score']).agg(Count=('order_id','count')).sort_values(['review_score','Count'],ascending=[True, False]).head(10)

                                    Count
product_category_name review_score
Bed_Bath_Table        1              1698
Furniture_Decor       1              1293
Computers_Accessories 1              1201
Health_Beauty         1              1135
Sports_Leisure        1              1066
Housewares            1               864
Watches_Gifts         1               780
Telephony             1               597
Garden_Tools          1               571
Auto                  1               530

---

In [549]:
# Top 10 rating by product 
merged_rating.groupby(['product_id','review_score']).agg(Count=('product_id','count')).sort_values(['review_score','Count'],ascending=[False, False]).head(10)

                                               Count
product_id                       review_score
422879e10f46682990de24d770e7f83d 5               272
aca2eb7d00ea1a7b8ebd4e68314663af 5               271
389d119b48cf3043d311335e499d9c6b 5               241
99a4788cb24856965c36a24e339b6058 5               238
368c6c730842d78016ad823897a372db 5               213
53759a2ecddad2bb87a079a1f1519f73 5               207
d1c427060a0f73f6b889a5c7c61f2ac4 5               207
53b36df67ebb7c41585e8d54d6772e08 5               193
154e7e31ebfa092203795c972e5804a6 5               190
3dd2a17168ec895c781a9191c1e95ad7 5               162

In [551]:
# Minimum 10 ratings by product id 
merged_rating.groupby(['product_id','review_score']).agg(Count=('product_id','count')).sort_values(['review_score','Count'],ascending=[True, False]).head(10)

                                               Count
product_id                       review_score
422879e10f46682990de24d770e7f83d 1                79
368c6c730842d78016ad823897a372db 1                66
53759a2ecddad2bb87a079a1f1519f73 1                65
99a4788cb24856965c36a24e339b6058 1                65
e53e557d5a159f5aa2c5e995dfdf244b 1                54
aca2eb7d00ea1a7b8ebd4e68314663af 1                52
b532349fe46b38fbc7bb3914c1bdae07 1                46
389d119b48cf3043d311335e499d9c6b 1                44
36f60d45225e60c7da4558b070ce4b60 1                43
d1c427060a0f73f6b889a5c7c61f2ac4 1                39

---

In [582]:
# Average rating by location 
merged_rating.groupby(['seller_city','seller_state']).agg(average_rating=('review_score','mean')).round(1)

                                average_rating
seller_city  seller_state
Aadityana    Gujarat                       1.0
Aarambhada   Gujarat                       4.3
Achabal      Jammu & Kashmir               4.0
Adalaj       Gujarat                       4.4
Adilabad     Andhra Pradesh                4.0
...                                        ...
Yellandu     Andhra Pradesh                4.2
Yemmiganur   Andhra Pradesh                4.2
Zahirabad    Andhra Pradesh                3.5
Ziauddin Pur Delhi                         3.9
Ziro         Arunachal Pradesh             3.5

[534 rows x 1 columns]

In [584]:
#Average rating by seller
merged_rating.groupby(['seller_id']).agg(average_rating=('review_score','mean')).round(1)

                                  average_rating
seller_id
0015a82c2db000af6aaaf3ae2ecb0532             3.7
001cca7ae9ae17fb1caed9dfb1094831             3.9
001e6ad469a905060d959994f1b41e4f             1.0
002100f778ceb8431b7a1020ff7ab48f             4.0
003554e2dce176b5555353e4f3555ac8             5.0
...                                          ...
ffcfefa19b08742c5d315f2791395ee5             1.0
ffdd9f82b9a447f6f8d4b91554cc7dd3             4.2
ffeee66ac5d5a62fe688b9d26f83f534             4.2
fffd5413c0700ac820c7069d66d98c89             3.9
ffff564a4f9085cd26170f4732393726             2.1

[3095 rows x 1 columns]

In [586]:
#Average rating by product
merged_rating.groupby(['product_id']).agg(average_rating=('review_score','mean')).round(1)

                                  average_rating
product_id
00066f42aeeb9f3007548bb9d3f33c38             5.0
00088930e925c41fd95ebfe695fd2655             4.0
0009406fd7479715e4bef61dd91f2462             1.0
000b8f95fcb9e0096488278317764d19             5.0
000d9be29b5207b54e86aa1b1ac54872             5.0
...                                          ...
fff6177642830a9a94a0f2cba5e476d1             4.5
fff81cc3158d2725c0655ab9ba0f712c             4.0
fff9553ac224cec9d15d49f5a263411f             5.0
fffdb2d0ec8d6a61f0a0a0db3f25b441             5.0
fffe9eeff12fcbd74a2f2b007dde0c58             4.0

[32951 rows x 1 columns]

In [588]:
# Average rating by category
merged_rating.groupby(['product_category_name']).agg(average_rating=('review_score','mean')).round(1)

                            average_rating
product_category_name
Agro_Industry_And_Commerce             4.0
Air_Conditioning                       3.9
Art                                    3.9
Arts_And_Craftmanship                  4.1
Audio                                  3.8
...                                    ...
Stationery                             4.2
Tablets_Printing_Image                 4.0
Telephony                              3.9
Toys                                   4.1
Watches_Gifts                          4.0

[71 rows x 1 columns]

In [595]:
# average category by month 
#to date time 
merged_rating['review_answer_timestamp'] = pd.to_datetime(merged_rating['review_answer_timestamp'])

# Extract month (e.g., 1 to 12)
merged_rating['review_month'] = merged_rating['review_answer_timestamp'].dt.month

merged_rating.groupby(['review_month']).agg(average_rating=('review_score','mean')).round(1)

              average_rating
review_month
1                        4.0
2                        4.0
3                        3.7
4                        3.8
5                        4.1
6                        4.1
7                        4.2
8                        4.2
9                        4.1
10                       4.1
11                       4.0
12                       3.8

<hr style="border: 2px solid black;">
<hr style="border: 2px solid black;">